Repository Taks0708/SOFTENG310-FinTrack, pull requests merged in 2024-09, with the labels that each got.

#149 Bugfix - Can't remove 0 when adding income
  frontend/src/components/TransactionForm.jsx
Labels: bug

#153 Refactor/database larger numbers
  backend/src/config/createTables.js
  frontend/src/components/AddTransactionButton.jsx
  frontend/src/components/SavingsTracker.jsx
Labels: bug, enhancement

#158 Feature/sign out
  frontend/src/components/Banner.jsx
Labels: feature

#159 refactor/backend testing for services
  backend/src/services/userService.js
  backend/test/service/securePassword.test.js
  backend/test/service/transactionService.test.js
  backend/test/service/userService.test.js
Labels: refactor

#154 Bugfix - Asynchronous errors when adding multiple transactions
  frontend/src/components/TransactionForm.jsx
Labels: bug

#165 [Bug] Issue #142: Edge case handling for transaction value of 0
  backend/src/controllers/transactionsController.js
  frontend/src/components/TransactionForm.jsx
Labels: bug

#167 only allow transaction amount that aligns with the database
  frontend/src/components/TransactionForm.jsx
Labels: enhancement
