Repository Taks0708/SOFTENG310-FinTrack, pull requests merged in 2024-10, with the labels that each got.

#187 Bugfix/change css
  frontend/src/assets/css/dashboard.css
  frontend/src/assets/css/defaultButton.css
  frontend/src/assets/css/variables.css
  frontend/src/components/metrics/SavingsTracker.jsx
  frontend/src/components/metrics/SetGoal.jsx
  frontend/src/components/progress-bar/CompletionMsg.jsx
  frontend/src/components/progress-bar/GoalBar.jsx
  frontend/src/pages/Dashboard.jsx
Labels: bug

#192 Feature/financial advice
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/luckyAdviserController.js
  backend/src/routes/luckyAdviser.js
  backend/src/server.js
  backend/src/services/responseCleaner.js
  frontend/src/components/gemini/LuckyAdviser.jsx
  frontend/src/components/gemini/LuckyButton.jsx
  frontend/src/components/gemini/ResponseCleaner.jsx
  frontend/src/pages/Dashboard.jsx
Labels: enhancement

#203 Bugfix/Unblock the cancel button in add transaction form
  frontend/src/components/transactions/TransactionForm.jsx
Labels: enhancement

#202 Doc/update README.md
  README.md
  frontend/src/components/gemini/LuckyAdviser.jsx
  frontend/src/components/gemini/ResponseCleaner.jsx
Labels: documentation

#193 Refactor/147 metrics refactor
  backend/src/controllers/transactionsController.js
  backend/src/routes/transactions.js
  frontend/src/components/TransactionLog.jsx
  frontend/src/components/metrics/FinancialMetrics.jsx
Labels: refactor

#209 Feature/responsive input
  frontend/src/components/gemini/LuckyAdviser.jsx
  frontend/src/components/gemini/LuckyButton.jsx
Labels: enhancement
